# This is the default base file to for fabric membersrvc

# Depends on the hyperledger/fabric-membersrvc image.

version: '2'

services:
  membersrvc:
      image: hyperledger/fabric-membersrvc:latest
      restart: unless-stopped
      expose:
        - "7054"
      volumes: # docker.sock is mapped as the default CORE_VM_ENDPOINT
        - /var/run/docker.sock:/var/run/docker.sock
      command: membersrvc  # this repeats the default cmd to make sure