# This is the default base file to config env and command
# Notice that chaincode is executed inside docker in default net mode


# This utilized the pbft as consensus


version: '2'

services:
  vp:  # vp node no needing membersrvc
    image: hyperledger/fabric-peer:latest
   
    restart: unless-stopped
    environment:
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_PEER_NETWORKID=dev
      - CORE_LOGGING_LEVEL=info  #critical, error, warning, notice, info, debug
      - CORE_PEER_VALIDATOR_CONSENSUS_PLUGIN=pbft  # noops, pbft
      - CORE_PBFT_GENERAL_MODE=batch  # batch. classic and sieve will be not supported again.
      - CORE_PBFT_GENERAL_N=4
      - CORE_PBFT_GENERAL_BATCHSIZE=2  # only useful when in batch mode
      - CORE_PBFT_GENERAL_TIMEOUT_REQUEST=2s
    expose:
      - "7050"  # Rest
      - "7051"  # Grpc
      - "7052"  # Peer CLI
      - "7053"  # Peer Event
      - "7054"  # eCAP
      - "7055"  # eCAA
      - "7056"  # tCAP
      - "7057"  # eCAA
      - "7058"  # tlsCAP
      - "7059"  # tlsCAA
    volumes: # docker.sock is mapped as the default CORE_VM_ENDPOINT
      - /var/run/docker.sock:/var/run/docker.sock
    command: peer node start  # this repeats the default cmd to make sure
  # command: sh -c "sleep 5; peer node start"  # peer node should have booting delay with CA

  vp_sec: # vp node needing membersrvc suppot
    extends:
      service: vp
    environment:
      - CORE_SECURITY_ENABLED=true
      - CORE_PEER_PKI_ECA_PADDR=membersrvc0:7054
      - CORE_PEER_PKI_TCA_PADDR=membersrvc0:7054
      - CORE_PEER_PKI_TLSCA_PADDR=membersrvc0:7054